# Demo build pipeline for api-gateway

trigger:
  branches:
    include:
    - azure
  paths:
    include:
    - spring-petclinic-visits-service/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - template : templates/stages/stage-build-unit-test-publish.yml
    parameters :
      stageName : build_vists_service
      pomPath : "pom.xml"
      buildGoals : '--pl spring-petclinic-visits-service  -Dmaven.test.skip=true clean install'
      jdkVersion : '1.17'
      unitTestGoals : '--pl spring-petclinic-visits-service  -DfailIfNoTests=false test'
      unitTestRunTitleName : "unit test results"