# ADO Pipeline
name: Azure Springs Apps LZA Deployment

trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: PC-SPRING-APP-DEV-ENVIRONMENT

#resources:
#  pipelines:
#  - pipeline : build_admin_server_dev
#    source  : build-admin-server-dev
#    trigger : true


#resources:
#  pipelines:
#  - pipeline: aUniqueNameHereForLocalReferenceCanBeAnything
#    project: projectNameNOTtheGUID
#    source: nameOfTheOtherPipelineNotTheDefinitionId
#    trigger:


stages:
  - template: "templates/stages/stage-deploy-asa.yml"
    parameters:
        stageName: deploy_appservice
        dependson: []
        serviceConnection: 'JB'
        resourceGroupName : $(resourceGroupName) 
        springAppName : $(springAppName)
        location : $(location)

  - template: "templates/stages/stage-deploy-spring-app.yml"
    parameters:
        stageName: deploy_admin_server
        dependson: [deploy_appservice]
        skipAppService : false
        serviceConnection: 'JB'
        namePrefix: $(namePrefix)
        buildType: 'specific'
        projectId: 'adc249cd-7a87-42f8-8e35-2da681ea24cf'
        definitionId: '53'
        buildVersionToDownload: 'latest'
        artifactName: 'drop'
        resourceGroupName : $(resourceGroupName) 
        springAppName : $(springAppName)
        appName : "admin-server-$(namePrefix)"
        targetArtifact: "spring-petclinic-admin-server/target/api-admin-server-3.0.1.jar"

  - template: "templates/stages/stage-run-integration-tests.yml"
    parameters:
      stageName: run_integration_tests
      dependson: [deploy_admin_server]     

  - template: "templates/stages/stage-destroy-spring-app.yml"
    parameters:
        stageName: destroy_admin_server
        dependson: [run_integration_tests]
        serviceConnection: 'JB'
        skipAppService : false
        ephemeral : true
        appName : "api-gateway-$(namePrefix)"
        resourceGroupName : $(resourceGroupName)
        springAppName : $(springAppName)

  - template: "templates/stages/stage-destroy-appservice.yml"
    parameters:
        stageName: destroy_appservice
        dependson: [destroy_admin_server]
        skipAppService : false
        ephemeral : true
        serviceConnection: 'JB'
        resourceGroupName : $(resourceGroupName) 
        springAppName : $(springAppName)