# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - azure
  paths:
    include:
    - spring-petclinic-visits-service
     
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: build
      steps:
      - task: Maven@3
        name : MavenBuild
        displayName: Build spring-petclinic-visits-service
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          codeCoverageToolOption: 'JaCoCo'
          pmdRunAnalysis: true
          checkStyleRunAnalysis: true
          goals: '--pl spring-petclinic-visits-service -am -q clean package'

    - job: copy
      steps:
      - task: CopyFiles@2
        inputs:
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - job: publish
      steps:
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
