# Deploy Petclinic Spring App Template
parameters:
  - name : stageName
    type : string
  - name : dependson
    type : object
  - name : serviceConnection
    type : string
  - name : resourceGroupName
    type : string
  - name : springAppName 
    type: string
  - name : skipAppService
    type : boolean

stages:
- stage: ${{parameters.stageName}}
  displayName: "Stage: Deploy Spring App service ${{parameters.springAppName}}"
  dependsOn: ${{parameters.dependson}}
  #condition: not(or(failed(), canceled()))
  jobs:
    - template: ../jobs/jobs-create-spring-appservice.yml
      parameters:
        jobName: "create_springappservice"
        dependson: []
        skipAppService : ${{parameters.skipAppService}}
        ignoreError: false
        serviceConnection: ${{parameters.serviceConnection}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        springAppServiceName: ${{parameters.springAppName}}
 